### ISSUE TITLE
Inconsistent behavior of `max_tokens` argument in JSON Mode vs free gen mode

### ISSUE THREAD

**Issue by Saibo-creator** [guidance-ai/guidance#1084]
**The bug**
When using Guidance with the LlamaCpp or HF backend to generate JSON outputs in "json mode" or "json schema mode" the actual number of tokens in the output does not match the expected token count specified in the `max_tokens` parameter. While free-form generation respects the expected token count, JSON mode generation produces fewer tokens than expected. 

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
from llama_cpp import Llama
import guidance
from guidance import gen, json

llamacpp_model = Llama.from_pretrained(
    repo_id="bartowski/Phi-3.5-mini-instruct-GGUF", filename="*Q5_K_M.gguf", n_ctx=1024, n_gpu_layers=-1
)
guidance_model_state = guidance.models.LlamaCpp(
llamacpp_model, echo=False
)

# HF backend gives the same bahavior
# guidance_model_state = guidance.models.Transformers(    "meta-llama/Meta-Llama-3.1-8B-Instruct", torch_dtype=torch.bfloat16, device_map="auto")

prompt = "Convert the following dictionary to a JSON schema: {'name': 'John', 'age': 30, 'city': 'New York'} ->"

################
#
# free form generation
#
################

output_state = guidance_model_state + prompt + gen(max_tokens=5, name="output")

output = output_state["output"]

# how many tokens are output

output_byte_string = output.encode("utf-8")
num_output_tokens = len(
    guidance_model_state.engine.tokenizer.encode(output_byte_string)
)

print(f"Expected number of tokens: 5, actual number of tokens: {num_output_tokens}")

# Expected number of tokens: 5, actual number of tokens: 5 ✅


################
#
# JSON mode generation
#
################


output_state = guidance_model_state + prompt + json(max_tokens=5, name="output")

output = output_state["output"]

# how many tokens are output

output_byte_string = output.encode("utf-8")

num_output_tokens = len(
    guidance_model_state.engine.tokenizer.encode(output_byte_string)
)

print(f"Expected number of tokens: 5, actual number of tokens: {num_output_tokens}")

# Expected number of tokens: 5, actual number of tokens: 3   ❓
```

**System info (please complete the following information):**
 - Guidance Version (`guidance.__version__`): `0.2.0rc`

**Comment by Saibo-creator** [comment]
Thanks for the quick respoonse !

I just tried to flip the order and the number also flipped.  

I had 

```
Expected number of tokens: 5, actual number of tokens: 5
Expected number of tokens: 5, actual number of tokens: 3
```

now 

```
Expected number of tokens: 5, actual number of tokens: 3
Expected number of tokens: 5, actual number of tokens: 5
```

**Comment by Saibo-creator** [comment]
But I remember I did try clear the engine state, and even if I just call the json mode, I still get this issue

```
from llama_cpp import Llama
import guidance
from guidance import gen, json

llamacpp_model = Llama.from_pretrained(
    repo_id="bartowski/Phi-3.5-mini-instruct-GGUF", filename="*Q5_K_M.gguf", n_ctx=1024, n_gpu_layers=-1
)
guidance_model_state = guidance.models.LlamaCpp(
llamacpp_model, echo=False
)

# HF backend gives the same bahavior
# guidance_model_state = guidance.models.Transformers(    "meta-llama/Meta-Llama-3.1-8B-Instruct", torch_dtype=torch.bfloat16, device_map="auto")

prompt = "Convert the following dictionary to a JSON schema: {'name': 'John', 'age': 30, 'city': 'New York'} ->"



################
#
# JSON mode generation
#
################


output_state = guidance_model_state + prompt + json(max_tokens=5, name="output")

output = output_state["output"]

# how many tokens are output

output_byte_string = output.encode("utf-8")

num_output_tokens = len(
    guidance_model_state.engine.tokenizer.encode(output_byte_string)
)

print(f"Expected number of tokens: 5, actual number of tokens: {num_output_tokens}")

# Expected number of tokens: 5, actual number of tokens: 3   ❓
```

**Comment by Harsha-Nori** [comment]
Can you paste the string of output too? max_tokens is just a maximum number, the grammar can terminate with less

**Comment by Saibo-creator** [comment]
`{"type":`

**Comment by Saibo-creator** [comment]
> Wait I'm a bit confused -- you're measuring the length of the output, not the input here, yes?

Oh, sorry about that, that's a typo in the code above. I'm measuing the output tokens

**Comment by hudson-ai** [comment]
@Harsha-Nori note that the kv cache isn't coming into play with measuring the number of tokens (although it's certainly affecting generation time on the second call)

**Comment by hudson-ai** [comment]
@Saibo-creator what's your guidance and llguidance version? On latest, I can't even get the json bit to run, as we hit an exception due to the max_tokens cutting off the output

**Comment by hudson-ai** [comment]
Sorry, maybe a bit orthogonal to the rest of the convo here.

**Comment by Saibo-creator** [comment]
This issue can be a bit frustrating when trying to determine if the model stopped because it reached the maximum output tokens. Normally, we would just check if the output tokens match the `max_output_tokens` value, but in this case, it’s not so straightforward. For example, with `max_output_tokens=2048`, the model might produce an output of around 1200 tokens and still get truncated.

**Comment by Saibo-creator** [comment]
```
llguidance=0.2.0
guidance=0.2.0rc1 with hash 958145ccc  Tue Sep 3
```

This is quite old version indeed

**Comment by Saibo-creator** [comment]
With the following version 

- llguidance = 0.4.1
- guidance = commit 50a5c from Tue Nov 26

I get:

```
Traceback (most recent call last):
  File "/home/saibo/dlabscratch1/geng/JsonSchemaBench/debug/models/guidance_model_example_debug_truncation2.py", line 46, in <module>
    output_state = guidance_model_state + prompt + json(max_tokens=5, name="output")
  File "/home/saibo/infrastructure/guidance_integrated_dev/guidance/guidance/models/_model.py", line 548, in __add__
    out = lm._run_stateless(value)
  File "/home/saibo/infrastructure/guidance_integrated_dev/guidance/guidance/models/_model.py", line 754, in _run_stateless
    for chunk in gen_obj:
  File "/home/saibo/infrastructure/guidance_integrated_dev/guidance/guidance/models/_model.py", line 174, in __call__
    parser.cleanup()
  File "/home/saibo/infrastructure/guidance_integrated_dev/guidance/guidance/_parser.py", line 164, in cleanup
    raise TokenParserException(f"Unexpected stop reason: {stop_reason}")
guidance._parser.TokenParserException: Unexpected stop reason: NoExtensionBias
```

So it seems that the current version will yied this error message when it produces something not satsifying the constraints due to early exiting ? This is good. I can just rely on this to detect the infinite looping cases :)
