### ISSUE TITLE
runtime error with Transformers and accelerate

### ISSUE THREAD

**Issue by Zhengbaibai** [guidance-ai/guidance#292]
**The bug**
When using guidance with transformers model, the following tensor mismatch error will occur. However it can NOT reproduce 100%.

**Stack Trace**
```
Exception in thread Thread-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 1574, in generate
    return self.sample(
  File "/usr/local/lib/python3.8/dist-packages/transformers/generation/utils.py", line 2621, in sample
    outputs = self(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/bloom/modeling_bloom.py", line 915, in forward
    transformer_outputs = self.transformer(
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/bloom/modeling_bloom.py", line 759, in forward
    causal_mask = self._prepare_attn_mask(
  File "/usr/local/lib/python3.8/dist-packages/transformers/models/bloom/modeling_bloom.py", line 668, in _prepare_attn_mask
    expanded_attn_mask if combined_attention_mask is None else expanded_attn_mask | combined_attention_mask
RuntimeError: The size of tensor a (170) must match the size of tensor b (212) at non-singleton dimension 3
```

First, I guess that the bug might be related to the caching mechanism.  
```
guidance.llms.LLM.cache.clear()
guidance.llm.caching = True
```
But neither of the above two ways can solve the problem. 
Then I think the problem might related to the model kwargs of `past_key_values`. I try to modify  `__enter__` function in `TransformersSession` Class. When I comment the code in `__enter__` function and just return, the problem is fixed.
```
def __enter__(self):
    return self
```
Therefore, there is a problem with processing decorators when using acceleration.

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
MODEL_ID = "bigscience/bloom-7b1"
tokenizer = BloomTokenizerFast.from_pretrained(MODEL_ID, padding_side="left")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
)
model = BloomForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map={"": torch.cuda.current_device()},
)

bloom = guidance.llms.Transformers(model=model, tokenizer=tokenizer)
guidance.llm = bloom

PROMPT_PLAN = """
### Input:
Today is {{current_time}}. Please make a plan today for {{name}} in broad strokes. Given the summary:
{{summary}}

### Response:
Here is {{name}}'s plan from now at {{current_time}}:
[From {{now}} to {{gen 'to' pattern='[0-9]+:[0-9][0-9]' stop=' ]'}}]: {{gen 'task' top_k=30 top_p=0.18 repetition_penalty=1.15 temperature=1.99 stop='\n'}}
"""

summary = "Sam is a Ph.D student, his major is CS.  Sam feels tired because of playing games"
prompt = guidance(PROMPT_PLAN, silent=False)
result = prompt(summary=summary,
                name="Sam",
                now=datetime.now().strftime('%H:%M'),
                current_time=datetime.now().strftime('%A %B %d, %Y, %H:%M')
                )
```

**System info (please complete the following information):**
 - OS : Ubuntu
 - Guidance Version (`guidance.__version__`): 0.0.64
 - Transformers Version: 4.31.0.dev0
 - accelerate 0.20.3

**Comment by zx12671** [comment]
@Zhengbaibai  Similary error in chatGLM6B2 .  Have you solved?

**Comment by kk19990709** [comment]
Have you solved?

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). Sorry it took us so long to get to it!

**Comment by tritola** [comment]
I still encounter the same issue with tensors not matching in
`expanded_attn_mask if combined_attention_mask is None else expanded_attn_mask | combined_attention_mask`
even with the new release when using any Bloom model.  Any solutions?
