### ISSUE TITLE
Examples are very confusing (or I am very confused)

### ISSUE THREAD

**Issue by lukehinds** [guidance-ai/guidance#371]
Many of the examples show a local model

`guidance.llm = guidance.llms.Transformers("your_local_path/llama-7b", device=0)`

Yet the code attempts to validate a repo ID and seems to want to use hugging face hub download?

```
Traceback (most recent call last):
  File "/Users/lhinds/repos/lukehinds/pkg-recommendation/main.py", line 4, in <module>
    guidance.llm = guidance.llms.Transformers(".\models\llama7b.bin", device=0)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lhinds/anaconda3/lib/python3.11/site-packages/guidance/llms/_transformers.py", line 32, in __init__
    self.model_obj, self.tokenizer = self._model_and_tokenizer(model, tokenizer, **kwargs)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lhinds/anaconda3/lib/python3.11/site-packages/guidance/llms/_transformers.py", line 99, in _model_and_tokenizer
    tokenizer = transformers.AutoTokenizer.from_pretrained(model, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lhinds/anaconda3/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 643, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/lhinds/anaconda3/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 487, in get_tokenizer_config
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/Users/lhinds/anaconda3/lib/python3.11/site-packages/transformers/utils/hub.py", line 417, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/Users/lhinds/anaconda3/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/Users/lhinds/anaconda3/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 164, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: '.\models\llama7b.bin'.
```

**Comment by joshuaipwork** [comment]
Yes, the examples are rather confusing. I find the most consistent way to do this is to create a pretrained model and tokenizer in transformers, then pass those in to `guidance.llms.Transformers(...)`.

**Comment by marcotcr** [comment]
Sorry, we're bad at writing READMEs. Hopefully the version we have in the [new release](https://github.com/guidance-ai/guidance/discussions/429) is a little better :)
