### ISSUE TITLE
Chat models for LLaMA 2 does not work

### ISSUE THREAD

**Issue by armsp** [guidance-ai/guidance#397]
When I try to use the chat models for LLaMA 2 then I get the following error -
```
Traceback (most recent call last):
  File "/cluster/home//llama/my_venv/lib64/python3.9/site-packages/guidance/_program_executor.py", line 109, in run
    await self.visit(self.parse_tree, VariableStack([self.program._variables], self))
  File "/cluster/home//llama/my_venv/lib64/python3.9/site-packages/guidance/_program_executor.py", line 559, in visit
    visited_children.append(await self.visit(child, variable_stack, inner_next_node, inner_next_next_node, inner_prev_node, node, parent_node))
  File "/cluster/home//llama/my_venv/lib64/python3.9/site-packages/guidance/_program_executor.py", line 524, in visit
    command_output = await command_function(*positional_args, **named_args)
  File "/cluster/home//llama/my_venv/lib64/python3.9/site-packages/guidance/library/_system.py", line 13, in system
    return await role(role_name="system", hidden=hidden, _parser_context=_parser_context, **kwargs)
  File "/cluster/home//llama/my_venv/lib64/python3.9/site-packages/guidance/library/_role.py", line 14, in role
    new_content += parser.program.llm.role_start(role_name, **kwargs)
  File "/cluster/home//llama/my_venv/lib64/python3.9/site-packages/guidance/llms/_transformers.py", line 72, in role_start
    raise NotImplementedError("In order to use chat role tags you need to use a chat-specific subclass of Transformers for your LLM from guidance.transformers.*!")
NotImplementedError: In order to use chat role tags you need to use a chat-specific subclass of Transformers for your LLM from guidance.transformers.*!

Error in program:  In order to use chat role tags you need to use a chat-specific subclass of Transformers for your LLM from guidance.transformers.*!
```
**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
import guidance
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer
# replace your_path with a version of the LLaMA model
model_path = "/llama2models/13b-chat-hf"
tokenizer = LlamaTokenizer.from_pretrained(
    model_path,
)
guidance.llm = guidance.llms.transformers.LLaMA(model_path, tokenizer=tokenizer, device_map="auto", token_healing=True, torch_dtype=torch.bfloat16,  load_in_8bit=False, load_in_4bit=False, temperature=0.7)
experts = guidance('''
{{#system~}}
You are a helpful and terse assistant.
{{~/system}}

{{#user~}}
I want a response to the following question:
{{query}}
Name 3 world-class experts (past or present) who would be great at answering this?
{{~/user}}

{{#assistant~}}
{{gen 'expert_names' temperature=0.6 max_tokens=300}}
{{~/assistant}}
''')

experts(query='How can I be more productive?')
print(experts)
```

**System info:**
 - OS - Ubuntu
 - Guidance Version - 0.0.64

**Comment by hitsz-zxw** [comment]
Have you resolved this issue? I'm facing the same problem.

**Comment by junz-debug** [comment]
may be you should use guidance==0.0.61? i am not sure. [https://github.com/iiis-ai/cumulative-reasoning/blob/main/requirements.txt](url)

**Comment by armsp** [comment]
@junz-debug Unfortunately i get the same error

**Comment by marcotcr** [comment]
Hopefully this is fixed in the [new release](https://github.com/guidance-ai/guidance/discussions/429). We played a lot with ChatLlama models, and I think they work. Sorry it took us so long to get to it! :)

**Comment by marcotcr** [comment]
(It's called `models.LlamaCppChat` now, see example in readme)
