### ISSUE TITLE
guidance==0.1.1 and OpenAI models. Can't run any examples from the tutorial. 

### ISSUE THREAD

**Issue by burmaxwell** [guidance-ai/guidance#442]
**The bug**
Have openai related errors during execution examples from the tutorial:

guidance==0.1.1
openai==1.3.0

```
Exception in thread Thread-32 (_start_generator_stream):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/guidance/models/_remote.py", line 99, in _start_generator_stream
    for chunk in generator:
  File "/usr/local/lib/python3.10/dist-packages/guidance/models/_openai.py", line 207, in _generator
    raise e
  File "/usr/local/lib/python3.10/dist-packages/guidance/models/_openai.py", line 197, in _generator
    generator = self.client.chat.completions.create(
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1055, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 834, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 877, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "[] is too short - 'messages'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Here is one of the example to reproduce**
```python
gpt = models.OpenAI("gpt-3.5-turbo")

@guidance
def character_maker(lm, id, description, valid_weapons):
    lm += f"""\
    The following is a character profile for an RPG game in JSON format.
    ```json
    {{
        "id": "{id}",
        "description": "{description}",
        "name": "{gen('name', stop='"')}",
        "age": {gen('age', regex='[0-9]+', stop=',')},
        "armor": "{select(options=['leather', 'chainmail', 'plate'], name='armor')}",
        "weapon": "{select(options=valid_weapons, name='weapon')}",
        "class": "{gen('class', stop='"')}",
        "mantra": "{gen('mantra', stop='"')}",
        "strength": {gen('strength', regex='[0-9]+', stop=',')},
        "items": ["{gen('item', list_append=True, stop='"')}", "{gen('item', list_append=True, stop='"')}", "{gen('item', list_append=True, stop='"')}"]
    }}```"""
    return lm

lm = gpt + character_maker(1, 'A nimble fighter', ['axe', 'sword', 'bow'])
```

**Comment by marcotcr** [comment]
`gpt-3.5-turbo` is a chat model, and thus you need to use the chat api, like this example from the readme:
```python
gpt = models.OpenAI("gpt-3.5-turbo")
with system():
    lm = gpt + "You are a cat expert."

with user():
    lm += "What are the smallest cats?"

with assistant():
    lm += gen("answer", stop=".")
```
Also, due to the limitations in the API, we cannot really constrain generation on OpenAI models, as this says in the readme:
> Remote endpoints that don't have explicit guidance integration are run "optimistically". This means that all the text that can be forced is given to the model as a prompt (or chat context) and then the model is run in streaming mode without hard constrants (since the remote API doesn't support them). If the model ever violates the contraints then the model stream is stopped and we optionally try it again at that point. This means that all the API-supported control work as expected, and more complex controls/parsing that is not supported by the API work if the model stays consistent with the program.

Thus, since we can only validate rather than constrain, you end up having to give more information to the model in the prompt.
