### ISSUE TITLE
Trouble importing guidance

### ISSUE THREAD

**Issue by riedgar-ms** [guidance-ai/guidance#504]
**The bug**

I just resynced with `main` and I cannot import `guidance` successfully

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
>>> import guidance
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/my/path/guidance/guidance/__init__.py", line 9, in <module>
    from . import models
  File "/my/path/guidance/guidance/models/__init__.py", line 1, in <module>
    from ._model import Model, Chat
  File "/my/path/guidance/guidance/models/_model.py", line 17, in <module>
    from .. import cpp
ImportError: cannot import name 'cpp' from partially initialized module 'guidance' (most likely due to a circular import) (/my/path/guidance/guidance/__init__.py)
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Happens on Windows and Ubuntu WSL
 - Guidance Version (`guidance.__version__`): Latest sync with `main`

**Comment by riedgar-ms** [comment]
OK, it appears I needed to do:
```bash
pip install pybind11
pip install --upgrade -e .[test]
```
