### ISSUE TITLE
guidance conda

### ISSUE THREAD

**Issue by BenSwisa** [guidance-ai/guidance#562]
cant seem to get guidance to work with transformers in a conda enviroment

created env with "conda create  -n llm-env -c huggingface transformers"

installed guidance with pip , since no option for conda install

ERROR:

Traceback (most recent call last):                                                                                               
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1184, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/models/__init__.py", line 15, in <module>
    from . import (
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/models/mt5/__init__.py", line 36, in <module>
    from ..t5.tokenization_t5_fast import T5TokenizerFast
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/models/t5/tokenization_t5_fast.py", line 24, in <module>
    from ...tokenization_utils_fast import PreTrainedTokenizerFast
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/tokenization_utils_fast.py", line 25, in <module>
    import tokenizers.pre_tokenizers as pre_tokenizers_fast
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/tokenizers/__init__.py", line 79, in <module>
    from .tokenizers import (
ImportError: libssl.so.10: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/guidance/models/transformers/_transformers.py", line 97, in _model_and_tokenizer
    tokenizer = transformers.AutoTokenizer.from_pretrained(model, use_fast=False, **kwargs)
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1174, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1186, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto because of the following error (look up to see its traceback):
libssl.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1184, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 26, in <module>
    from ...tokenization_utils import PreTrainedTokenizer
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 26, in <module>
    from .tokenization_utils_base import (
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 75, in <module>
    from tokenizers import AddedToken
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/tokenizers/__init__.py", line 79, in <module>
    from .tokenizers import (
ImportError: libssl.so.10: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bensw/test_Ws/guidance_test.py", line 4, in <module>
    gpt = models.Transformers(model)
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/guidance/models/transformers/_transformers.py", line 29, in __init__
    self.model_obj, self._orig_tokenizer = self._model_and_tokenizer(model, tokenizer, **kwargs)
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/guidance/models/transformers/_transformers.py", line 105, in _model_and_tokenizer
    tokenizer = transformers.AutoTokenizer.from_pretrained(model, use_fast=True, **kwargs) # fall back to the fast tokenizer
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1175, in __getattr__
    value = getattr(module, name)
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1174, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/bensw/anaconda3/envs/llm-env/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1186, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.auto.tokenization_auto because of the following error (look up to see its traceback):
libssl.so.10: cannot open shared object file: No such file or directory

**Comment by slundberg** [comment]
Can you post two snippets? One that fails with guidance, and one that works if you use transformers directly? thanks

**Comment by riedgar-ms** [comment]
Is this still an issue?
