### ISSUE TITLE
Report ConstraintException when using guidance GPT-4 with ThreadPool.

### ISSUE THREAD

**Issue by SwordFaith** [guidance-ai/guidance#601]
**The bug**
Report ConstraintException when using guidance GPT-4 with ThreadPool.

```
Traceback (most recent call last):
  File "/home/longxiang/lx/annotations_2_4b/batch_run_logi_qa_explaination.py", line 78, in <module>
    result = future.result()
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/longxiang/lx/annotations_2_4b/batch_run_logi_qa_explaination.py", line 56, in get_explaination_helper
    lm = lm + get_explaination(text, output)
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/site-packages/guidance/models/_model.py", line 306, in __add__
    out = value(lm)
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/site-packages/guidance/_grammar.py", line 45, in __call__
    return self.f(model, *self.args, **self.kwargs)
  File "/home/longxiang/lx/annotations_2_4b/batch_run_logi_qa_explaination.py", line 45, in get_explaination
    lm += gen("explaination", max_tokens=500, temperature=0.8, stop=["Question:", "<|im_end|>"])
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/site-packages/guidance/models/_model.py", line 302, in __add__
    out = lm._run_stateless(value)
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/site-packages/guidance/models/_model.py", line 465, in _run_stateless
    for new_bytes, is_generated, new_bytes_prob, capture_groups, capture_group_log_probs, new_token_count in gen_obj:
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/site-packages/guidance/models/_model.py", line 785, in __call__
    logits = self._get_logits(token_ids, parser.bytes[start_pos:forced_pos], current_temp)
  File "/home/longxiang/miniconda3/envs/lx_py310/lib/python3.10/site-packages/guidance/models/_remote.py", line 216, in _get_logits
    raise self._report_failed_match(prompt)
guidance.models._model.ConstraintException: The model attempted to generate b' love chili\nThis option tells us aboutTh...' after the prompt `b'...anation:<|im_end|><|im_start|>assistant\n'`, but that does
not match the given grammar constraints! Since your model is a remote API that does not support full guidance
integration we cannot force the model to follow the grammar, only flag an error when it fails to match.
You can try to address this by improving the prompt, making your grammar more flexible, rerunning with
a non-zero temperature, or using a model that supports full guidance grammar constraints.
```

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
# put your code snippet here
import os
import json
import guidance
from guidance import models, gen, system, user, assistant
import tiktoken
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from copy import deepcopy
import threading
import time


MAX_THREADS = 2
SEM_FACTOR = 4
semaphore = threading.Semaphore(MAX_THREADS * SEM_FACTOR)
ST = 0
ED = 20


base_dir = "data/"
with open(os.path.join(base_dir, "logiqa_train.jsonl"), "r") as f:
    data_group_list = json.load(f)

tokenizer = tiktoken.encoding_for_model("gpt-4")
gpt4 = models.OpenAI(
    model="gpt-4-1106-preview",
    tokenizer=tokenizer,
    api_key="<a secret key>",
    echo=False
)


@guidance
def get_explaination(lm, question, answer):
    with system():
        lm = (
            lm
            + "You are an expert in creating logic and common sense reasoning questions. Now, there are some questions and answers that require your detailed explanation. Please ensure that each explanation is clear and precise, and presents the reasoning process in a step-by-step manner. For choice questions, please explain why the correct answer is correct and why the other choices are incorrect. For open-ended questions, please explain the reasoning process of the answer."
        )

    with user():
        lm += f"Question: {question}\nAnswer: {answer}\nExplanation:"

    with assistant():
        lm += gen("explaination", max_tokens=500, temperature=0.8, stop=["Question:", "<|im_end|>"])

    return lm


def get_explaination_helper(lm, data_group):
    
    options_text = "\n".join(data_group["choices"])
    text = f"{data_group['question']}\n{options_text}"
    output = f"{data_group['ans'].upper()}."
    with semaphore:
        lm = lm + get_explaination(text, output)
        explaination = lm.get("explaination")
        del lm
    result = {
        "input": f"<用户>Q:{text}\nA:<AI>",
        "output": f"{explaination}.\n\nThe answer is {output}",
    }
    
    return result


_data_group_list = data_group_list[ST:ED]
with ThreadPoolExecutor(max_workers=MAX_THREADS) as executor:
    futures = []
    for data_group in tqdm(
        _data_group_list, total=len(_data_group_list), desc="submit job"
    ):
        futures.append(executor.submit(get_explaination_helper, gpt4, data_group))
        time.sleep(0.1)
    results = []
    for future in tqdm(as_completed(futures), total=len(futures), desc="get result"):
        with open(os.path.join(base_dir, "logiqa_explaination.jsonl"), "a") as f:
            result = future.result()
            f.write(json.dumps(result) + "\n")

```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Ubuntu
 - Guidance Version (`guidance.__version__`): 0.1.10

**Comment by slundberg** [comment]
Hmm. I ran this and got no error when I made up the missing data. (I used the branch in #586) If you still see issues perhaps post a smaller example. Thanks!
