### ISSUE TITLE
Exception on `gen()` with Phi2

### ISSUE THREAD

**Issue by riedgar-ms** [guidance-ai/guidance#609]
**The bug**

I'm getting a lot of exceptions when trying to run `guidance` on Phi2. These are usually an assertion error.

**To Reproduce**
Give a full working code snippet that can be pasted into a notebook cell or python file. Make sure to include the LLM load step so we know which model you are using.
```python
# Model loaded with
torch.set_default_device("cuda")
guidance_model = guidance.models.Transformers(
    "microsoft/phi-2", device=0, echo=False
)

# Consumed via:
    lm += dedent(
        f"""Answer the occupation of {short_biography} and generate the answer as json format.
        Here is an example: {{"name": , "occupation": ,}}. 
        Now generate the answer:
"""
    )
    _logger.info(f"lm: {lm}")
    lm += gen(name="model_answer")
```

where `short_biography` may be (e.g.):

 > PERSON is a senior journalist working with the weekend newspapers at COMPANY NAME. He graduated with a degree in journalism of UNIVERSITY, PLACE in DATE. His first job in journalism was as a freelance reporter for NEWSPAPER and later for COMPANY NAME. In DATE he became a full-time staff writer for COMPANY NAME.

(data redacted)

The particular exception in this case was:
```
['Traceback (most recent call last):
', '  File "/azureml-envs/azureml_ffc36ef8b027a79a3369b12d952c219c/lib/python3.11/site-packages/aether_utils/jsonl_utils.py", line 45, in line_map
    nxt_output = map_func(nxt)
                 ^^^^^^^^^^^^^
', '  File "/mnt/azureml/cr/j/26440dbcbea64ef7963feda3ca29e616/exe/wd/./jsonl_guidance_phi2.py", line 60, in __call__
    result = self._guidance_function(self._model, item, common=self._common_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
', '  File "/mnt/azureml/cr/j/26440dbcbea64ef7963feda3ca29e616/cap/data-capability/wd/INPUT_guidance_program/simple_biosbias_json_completion_v2.py", line 41, in guidance_generation
    result = lm + zeroshot_biosbias_json(short_biography=input["context"])
             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
', '  File "/azureml-envs/azureml_ffc36ef8b027a79a3369b12d952c219c/lib/python3.11/site-packages/guidance/models/_model.py", line 306, in __add__
    out = value(lm)
          ^^^^^^^^^
', '  File "/azureml-envs/azureml_ffc36ef8b027a79a3369b12d952c219c/lib/python3.11/site-packages/guidance/_grammar.py", line 45, in __call__
    return self.f(model, *self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
', '  File "/mnt/azureml/cr/j/26440dbcbea64ef7963feda3ca29e616/cap/data-capability/wd/INPUT_guidance_program/simple_biosbias_json_completion_v2.py", line 30, in zeroshot_biosbias_json
    lm += gen(name="model_answer")
', '  File "/azureml-envs/azureml_ffc36ef8b027a79a3369b12d952c219c/lib/python3.11/site-packages/guidance/models/_model.py", line 302, in __add__
    out = lm._run_stateless(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^
', '  File "/azureml-envs/azureml_ffc36ef8b027a79a3369b12d952c219c/lib/python3.11/site-packages/guidance/models/_model.py", line 465, in _run_stateless
    for new_bytes, is_generated, new_bytes_prob, capture_groups, capture_group_log_probs, new_token_count in gen_obj:
', '  File "/azureml-envs/azureml_ffc36ef8b027a79a3369b12d952c219c/lib/python3.11/site-packages/guidance/models/_model.py", line 638, in __call__
    token_ids,token_byte_positions = self._cleanup_tokens(token_ids,token_byte_positions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
', '  File "/azureml-envs/azureml_ffc36ef8b027a79a3369b12d952c219c/lib/python3.11/site-packages/guidance/models/_model.py", line 611, in _cleanup_tokens
    assert token_byte_positions[-1] == last_pos
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
', 'AssertionError
']
```

**System info (please complete the following information):**
 - OS (e.g. Ubuntu, Windows 11, Mac OS, etc.): Ubuntu 22.04
 - Python: 3.11
 - Guidance Version (`guidance.__version__`): guidance-0.1.10-cp311-cp311-manylinux_2_17_x86_64
 - pytorch: torch-2.2.0%2Bcu118-cp311-cp311-linux_x86_64

**Comment by riedgar-ms** [comment]
A fully working repro case:

```python
import torch
import guidance

from guidance import gen, models

torch.set_default_device("cuda")
guidance_model = guidance.models.Transformers("microsoft/phi-2")

prompt = """Answer the occupation of Clodia is a Roman-born poet who immigrated to the Sassanids in 372. Her poems and translations have appeared in Old Glyphs, 0500, Antipode, Word Disturbance, Pear Hillock Review, and many others. A three-time Applecart Prize and Excellence of the Net nominee, she is the author of Gabriel & Leviathan (Tyre Publishing, Sidon, 218), Systemet (Warm Rim Press, Zeeland, 212), and A Via Drapes from the Heavens (29th Abode Publishing, Gaul, 213). She co-edited and co-translated Piercing Perspective, an Anthology of Contemporary Roman Poetry (Lucky Charm Publishing, 261). More at notbyzantineyet.tumblr.com/. and generate the answer as json format.
Here is an example: {"name": , "occupation": ,}.
Now generate the answer:
"""

lm = guidance_model + prompt

lm += gen("model_output")
```

which produces output:

```
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.11it/s]
Traceback (most recent call last):
  File "/home/riedgar/debugging/./phi_debug.py", line 16, in <module>
    lm += gen("model_output")
  File "/home/riedgar/guidance/guidance/models/_model.py", line 330, in __add__
    out = lm._run_stateless(value)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riedgar/guidance/guidance/models/_model.py", line 521, in _run_stateless
    for new_bytes, is_generated, new_bytes_prob, capture_groups, capture_group_log_probs, new_token_count in gen_obj:
  File "/home/riedgar/guidance/guidance/models/_model.py", line 694, in __call__
    token_ids,token_byte_positions = self._cleanup_tokens(token_ids,token_byte_positions)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/riedgar/guidance/guidance/models/_model.py", line 667, in _cleanup_tokens
    assert token_byte_positions[-1] == last_pos
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
with CUDA 12 and torch 2.2.0. And a just-cloned `guidance` repo

**Comment by slundberg** [comment]
Thanks @riedgar-ms ! Just pushed a fix

**Comment by Pedrexus** [comment]
Sorry, but is this fixed? I tried the same example @riedgar-ms provided and got this error:

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[7], [line 16](vscode-notebook-cell:?execution_count=7&line=16)
      [9](vscode-notebook-cell:?execution_count=7&line=9) prompt = """Answer the occupation of Clodia is a Roman-born poet who immigrated to the Sassanids in 372. Her poems and translations have appeared in Old Glyphs, 0500, Antipode, Word Disturbance, Pear Hillock Review, and many others. A three-time Applecart Prize and Excellence of the Net nominee, she is the author of Gabriel & Leviathan (Tyre Publishing, Sidon, 218), Systemet (Warm Rim Press, Zeeland, 212), and A Via Drapes from the Heavens (29th Abode Publishing, Gaul, 213). She co-edited and co-translated Piercing Perspective, an Anthology of Contemporary Roman Poetry (Lucky Charm Publishing, 261). More at notbyzantineyet.tumblr.com/. and generate the answer as json format.
     [10](vscode-notebook-cell:?execution_count=7&line=10) Here is an example: {"name": , "occupation": ,}.
     [11](vscode-notebook-cell:?execution_count=7&line=11) Now generate the answer:
     [12](vscode-notebook-cell:?execution_count=7&line=12) """
     [14](vscode-notebook-cell:?execution_count=7&line=14) lm = guidance_model + prompt
---> [16](vscode-notebook-cell:?execution_count=7&line=16) lm += gen("model_output")

File [~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:302](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:302), in Model.__add__(self, value)
    [300](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:300) # run stateless functions (grammar nodes)
    [301](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:301) elif isinstance(value, StatelessFunction):
--> [302](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:302)     out = lm._run_stateless(value)
    [304](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:304) # run stateful functions
    [305](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:305) else:
    [306](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:306)     out = value(lm)

File [~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:465](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:465), in Model._run_stateless(lm, stateless_function, temperature, top_p, n)
    [463](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:463) delayed_bytes = b""
    [464](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:464) # last_is_generated = False
--> [465](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:465) for new_bytes, is_generated, new_bytes_prob, capture_groups, capture_group_log_probs, new_token_count in gen_obj:
    [466](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:466) 
    [467](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:467)     # we make everything full probability if we are not computing uncertainty
    [468](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:468)     if not lm.compute_log_probs:
    [469](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:469)         new_bytes_prob = 1.0

File [~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:638](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:638), in Model.__call__(self, grammar, max_tokens, n, top_p, temperature, ensure_bos_token)
    [636](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:636) # run a simple tokenizer (that does not use a grammar) on the prefix for better performance
    [637](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:637) token_ids,token_byte_positions = self._tokenize_prefix(prompt)
--> [638](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:638) token_ids,token_byte_positions = self._cleanup_tokens(token_ids,token_byte_positions)
    [639](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:639) if len(token_byte_positions) > 0:
    [640](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:640)     pre_parser_bytes = token_byte_positions[-1]

File [~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:611](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:611), in Model._cleanup_tokens(self, token_ids, token_byte_positions)
    [609](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:609)         for i in range(1, len(token_byte_positions)):
    [610](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:610)             token_byte_positions[i] -= 1
--> [611](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:611)     assert token_byte_positions[-1] == last_pos
    [613](https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c6369666572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f706564726f2f446f63756d656e74732f63616c63696665722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d-0040ssh-002dremote-002bcv0.vscode-resource.vscode-cdn.net/workspaces/calcifer/notebooks/~/.pyenv/versions/3.11.7/lib/python3.11/site-packages/guidance/models/_model.py:613) return token_ids, token_byte_positions

AssertionError:

**Comment by riedgar-ms** [comment]
@Pedrexus I don't believe there has been a PyPI release with the fix, if that's what you mean. Or are you seeing the above when installing from GitHub?
